### ISSUE TITLE
Labels.lua error

### ISSUE THREAD

**Issue by Galthariel** [erglo/wow-mission-report-button-plus#13]
Getting the following error randomly.

2x ...rfaceMissionReportButtonPlus/data/labels.lua:268: attempt to index field 'labels' (a nil value)
[string "@MissionReportButtonPlus/data/labels.lua"]:268: in function `CleanUpLabels'
[string "@MissionReportButtonPlus/MissionReportButtonPlus.lua"]:89: in function <.../MissionReportButtonPlus/MissionReportButtonPlus.lua:76>

Locals:
self = <table> {
 InitializeLabels = <function> defined @MissionReportButtonPlus/data/labels.lua:203
 GetLabel = <function> defined @MissionReportButtonPlus/data/labels.lua:257
 CleanUpLabels = <function> defined @MissionReportButtonPlus/data/labels.lua:267
 SaveLabel = <function> defined @MissionReportButtonPlus/data/labels.lua:240
 LoadInGameLabels = <function> defined @MissionReportButtonPlus/data/labels.lua:283
 IsEmptyLabel = <function> defined @MissionReportButtonPlus/data/labels.lua:221
}
(*temporary) = <function> defined @SharedXML/TableUtil.lua:361
(*temporary) = nil
(*temporary) = "enUS"
(*temporary) = "attempt to index field 'labels' (a nil value)"
L = <table> {
 CFG_DDMENU_NAMING_TEXT = "Prefer Expansion Names"
 CFG_ADDONINFOS_AUTHOR = "Author"
 CFG_DDMENU_ICONHINTALL_TEXT = "Only after Finishing ALL Missions"
 CFG_DDMENU_ENTRYTOOLTIP_GARRISON_INVASION_ALERT_TOOLTIP = "Shows an alert when an invasion in your Garrison is active."
 showLegionAssaultsInfo = "Legion Assault"
 CFG_DDMENU_ENTRYTOOLTIP_LABEL = "Details Tooltip"
 CFG_DDMENU_ENTRYTOOLTIP_MISSION_INFO_TOOLTIP = "Displays a brief summary of your currently active missions you started at the mission table."
 WORK_IS_EXPERIMENTAL_TOOLTIP_ADDITION = "(This function is experimental and under development. It might deliver incomplete information or might even not work properly.)"
 CFG_CHAT_NOTIFY_TEXT = "Toggle Chat Notifications"
 ENTRYTOOLTIP_DF_HIDE_MF_UNLOCK_DESCRIPTION_LABEL = "Hide Unlock Description"
 CFG_WOD_HIDE_GARRISON_INVASION_ALERT_ICON_TEXT = "Hide Alert Icon"
 CFG_DDMENU_ENTRYTOOLTIP_SHOW_TOOLTIP = "On mouse-over each menu item details about the corresponding expansion are shown in a tooltip.|n|nIf disabled, this tooltip will not appear."
 applyInvasionColors = "Apply Invasion Colors"
 CFG_DDMENU_ICONHINT_TOOLTIP = "After each menu item an exclamation mark icon appears as soon as an in-progress mission is finished.|n|nIf disabled, the icon will not be displayed."
 CFG_DDMENU_ENTRYTOOLTIP_FACTION_COLORS_TOOLTIP = "Displays the faction names in their respective colors."
 showGrandHuntsInfo = "Grand Hunts"
 CFG_DDMENU_STYLESELECTION_LABEL = "Menu Style"
 CFG_DDMENU_ENTRYTOOLTIP_DRAGON_GLYPHS_TOOLTIP = "Shows the progress of your Dragon Glyphs collection of each zone."
 CFG_DDMENU_STYLESELECTION_VALUE1_TEXT = "Tooltip Style"
 CFG_DDMENU_ENTRYTOOLTIP_BFA_BOUNTIES_TOOLTIP = "Lists the currently active Emissary Quests available on Zandalar and Kul Tiras in the tooltip."
 showCovenantBounties = "Callings"
 applyBfAFactionColors = "Apply Faction Colors"
 CFG_DDMENU_ENTRYTOOLTIP_EVENT_POI_ELEMENTAL_STORMS = "the Elemental Storms on the Dragon Isles"
 CFG_DDMENU_ENTRYTOOLTIP_EVENT_POI_ISKAARA_FEAST = "the Community Feast of the Iskaara Tuskarr"
 TOC_FILE_NOTES = "Adds a right-click menu to the mission reports button on the minimap|nwith access to reports from current and previous expansions."
 showBfAFactionAssaultsInfo = "Faction Assaults"
 CFG_DDMENU_ENTRYTOOLTIP_EVENT_POI_TIME_RIFTS = "the Time Rifts in Thaldraszus"
 CFG_DDMENU_ENTRYSELECTION_TEXT_D = "%d |4menu item:menu items; selected"
 showNzothThreats = "N'Zoth Assaults"
 CFG_DDMENU_ENTRYTOOLTIP_EVENT_POI_HIDE_EVENT_DESCRIPTIONS = "Hides additional event description texts when enabled."
 showMajorFactionRenownLevel = "Major Factions (Renown)"
 showLegionBounties = "Emissary Quests"
 CFG_DDMENU_SORTORDER_TOOLTIP = "The dropdown menu items are by default sorted by expansion release; eg. the current expansion comes first, the one before that next, etc.|n|nIf enabled, the sorting order will be reversed."
 autoHideCompletedDragonGlyphZones = "Hide Completed Zones"
 CFG_MINIMAPBUTTON_SHOWBUTTON_TOOLTIP = "As long as you haven't reached the highest level available for an extension by WoW default the minimap button for the expansion/garrison landing page remains hidden.|n|nIf enabled, this option shows you the button again with access to your last command table along with additional informations

**Comment by erglo** [comment]
Thanks for reporting this! I will tend to this as soon as possible.
