### ISSUE TITLE
Legion Status not working

### ISSUE THREAD

**Issue by Guino13** [erglo/wow-mission-report-button-plus#15]
Hello, there appears to be an issue with Legion on your new updates.  If it is selected the Right Key function does not work.  If Legion is unselected the Right Click function works as expected.  This only affects toons that have been to Legion and started the Hall quests.     Thank you.

**Comment by erglo** [comment]
Thank you for reporting this.
Try and type into chat `/mrbp hook`. This reapplies the mouse key hooks and binds them to the minimap button.
Sometimes other addons collide with this one when they try to use the minimap button as well.

**Comment by Guino13** [comment]
Hello,Thank you for looking at this issue. I tried your fix and it is still not working. Any other thoughts?Thank you. Jim OrmondOn Aug 9, 2023, at 16:10, Erwin D. Glockner ***@***.***> wrote:﻿
Thank you for reporting this.
Try and type into chat /mrbp hook. This reapplies the mouse key hooks and binds them to the minimap button.
Sometimes other addons collide with this one when they try to use the minimap button as well.

**Comment by pepedressingroom** [comment]
If the alt have not completed the legion unlocking quest, the legion unlocking quest tooltip do not show quest name in local language. for example, legion tooltip shows: "Rise, Champions" while other expansion tooltip show correct localized language same with client.
If the alt have completed the legion unlocking quest, this lua error occurs, when right click the expansion button.

```
Message: Interface/SharedXML/TableUtil.lua:366: bad argument #1 to 'next' (table expected, got nil)
Time: Sat Aug 12 14:45:08 2023
Count: 1
Stack: Interface/SharedXML/TableUtil.lua:366: bad argument #1 to 'next' (table expected, got nil)
[string "=[C]"]: in function `next'
[string "@Interface/SharedXML/TableUtil.lua"]:366: in function `TableHasAnyEntries'
[string "@Interface/AddOns/MissionReportButtonPlus/MissionReportButtonPlus.lua"]:1099: in function <.../MissionReportButtonPlus/MissionReportButtonPlus.lua:968>
[string "@Interface/AddOns/MissionReportButtonPlus/MissionReportButtonPlus.lua"]:1356: in function `initFunction'
[string "@Interface/SharedXML/UIDropDownMenu.lua"]:80: in function `UIDropDownMenu_Initialize'
[string "@Interface/SharedXML/UIDropDownMenu.lua"]:1166: in function <Interface/SharedXML/UIDropDownMenu.lua:1023>
[string "=[C]"]: in function `ToggleDropDownMenu'
[string "@Interface/AddOns/MissionReportButtonPlus/MissionReportButtonPlus.lua"]:1541: in function <.../MissionReportButtonPlus/MissionReportButtonPlus.lua:1536>

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
```

**Comment by erglo** [comment]
Hi there, sorry for the very late response. Due to health issues I had to limit my screen time to a minimum.
Thank you for the error log report! This is always a great help. A quick peak into it shows me, that I was looking in the wrong direction for this error, when I tried to reproduce it.
I will tend to it and try to release a fix within this week.

**Comment by Guino13** [comment]
Good day to you,

I hope you are feeling better.  I look forward to your update.

Thank you and have a good day!


James Ormond
917 Clipper Drive
Henderson, NV 89015
702.236.4972
***@***.***

**Comment by erglo** [comment]
Hey there,
I just uploaded a new version with the fix. It should work now as usual.
- Have fun!

**Comment by Guino13** [comment]
Good day,

I just tested it and it looks great.  

Thank you!


James Ormond
917 Clipper Drive
Henderson, NV 89015
702.236.4972
***@***.***
