### ISSUE TITLE
Not working in 10.1.7

### ISSUE THREAD

**Issue by hollo6** [erglo/wow-mission-report-button-plus#17]
Getting the following LUA error when right-clicking on the mission button and then nothing shows up.

2x ...onReportButtonPlus/MissionReportButtonPlus_Utils.lua:948: attempt to compare two nil values
[string "@MissionReportButtonPlus/MissionReportButtonPlus_Utils.lua"]:948: in function <...onReportButtonPlus/MissionReportButtonPlus_Utils.lua:948>
[string "=[C]"]: in function `sort'
[string "@MissionReportButtonPlus/MissionReportButtonPlus_Utils.lua"]:949: in function `GetAllMajorFactionDataForExpansion'
[string "@MissionReportButtonPlus/MissionReportButtonPlus.lua"]:796: in function <.../MissionReportButtonPlus/MissionReportButtonPlus.lua:795>
[string "@MissionReportButtonPlus/MissionReportButtonPlus.lua"]:1151: in function <.../MissionReportButtonPlus/MissionReportButtonPlus.lua:968>
[string "@MissionReportButtonPlus/MissionReportButtonPlus.lua"]:1356: in function `initFunction'
[string "@SharedXML/UIDropDownMenu.lua"]:80: in function `UIDropDownMenu_Initialize'
[string "@SharedXML/UIDropDownMenu.lua"]:1166: in function <SharedXML/UIDropDownMenu.lua:1023>
[string "=[C]"]: in function `ToggleDropDownMenu'
[string "@MissionReportButtonPlus/MissionReportButtonPlus.lua"]:1541: in function <.../MissionReportButtonPlus/MissionReportButtonPlus.lua:1536>

Locals:
a = <table> {
 unlockDescription = "Complete the quest Smells Like Loamm near Loamm in Zaralek Cavern."
 renownReputationEarned = 125
 bountySetID = 119
 renownLevel = 20
 isUnlocked = false
 factionID = 2564
 expansionID = 9
 celebrationSoundKit = 213204
 name = "Loamm Niffen"
 renownFanfareSoundKitID = 213208
 uiPriority = 5
 textureKit = "Niffen"
 renownLevelThreshold = 2500
}
b = <table> {
 unlockDescription = "Complete the quest Maruukai with the centaur caravan in the Ohn'ahran Plains."
 renownReputationEarned = 81
 bountySetID = 119
 renownLevel = 25
 isUnlocked = true
 factionID = 2503
 expansionID = 9
 celebrationSoundKit = 213204
 name = "Maruuk Centaur"
 renownFanfareSoundKitID = 213208
 uiPriority = 3
 textureKit = "Centaur"
 renownLevelThreshold = 2500
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare two nil values"

**Comment by erglo** [comment]
Thanks for reporting this. I will take a look at this error as soon as possible.

**Comment by erglo** [comment]
Hi, thanks again for reporting this.
Thanks to @justinkb who send a quick fix PR, I could quickly release a new version. The addon should work as expected now.

**Comment by hollo6** [comment]
Yes indeed it does, saw your commit and tried it right away and it works, thank you!
