### ISSUE TITLE
Assertion failed in CreateSettingsButtonInitializer (following WoW update to 10.2.0)

### ISSUE THREAD

**Issue by SpareSimian** [erglo/wow-mission-report-button-plus#19]
```
Date: 2023-11-07 18:11:38
ID: 1
Error occured in: Global
Count: 1
Message: ...face/SharedXML/Settings/Blizzard_SettingControls.lua line 576:
   assertion failed!
Debug:
   [string "=[C]"]: assert()
   [string "@Interface/SharedXML/Settings/Blizzard_SettingControls.lua"]:576: CreateSettingsButtonInitializer()
   [string "@Interface/AddOns/MissionReportButtonPlus/MissionReportButtonPlus_Options.lua"]:594: MRBP_Settings_Register()
   [string "@Interface/AddOns/MissionReportButtonPlus/MissionReportButtonPlus.lua"]:300: OnLoad()
   [string "@Interface/AddOns/MissionReportButtonPlus/MissionReportButtonPlus.lua"]:83:
      .../MissionReportButtonPlus/MissionReportButtonPlus.lua:76
```

**Comment by SpareSimian** [comment]
I'm still digging to find source for the changed API but have started here: https://warcraft.wiki.gg/wiki/Patch_10.2.0/API_changes

**Comment by SpareSimian** [comment]
See diff 12 here. Looks like there's a new boolean argument to the API, "addSearchTags". https://github.com/Gethe/wow-ui-source/compare/10.1.7..ptr2

Your new code should probably add two new arguments, nil and true, like this:
```
	local checkAllInitializer = CreateSettingsButtonInitializer('', CHECK_ALL, OnCheckAll, nil, true);  --> WoW global string
	layout:AddInitializer(checkAllInitializer);
	local unCheckAllInitializer = CreateSettingsButtonInitializer('', UNCHECK_ALL, OnUncheckAll, nil, true);  --> WoW global string
```

**Comment by erglo** [comment]
As always, thanks for reporting this!
I didn't have much time recently to prepare for WoW patch 10.2, so it was just a matter of time until something comes up.
It seems that you even provided a possible solution. Also, thanks for that.
As soon as I get home I will look into it.

**Comment by erglo** [comment]
Fixed. Also added `Superbloom` event details.
Thanks again for reporting this.
