### ISSUE TITLE
Compare Number with Nil Error

### ISSUE THREAD

**Issue by nancikennedy** [erglo/wow-mission-report-button-plus#25]
On Retail (11.0.2), using MRBP v1.1.0, I'm getting the following error:

1x .../MissionReportButtonPlus/MissionReportButtonPlus.lua:846: attempt to compare number with nil
[string "@MissionReportButtonPlus/MissionReportButtonPlus.lua"]:846: in function `ShowMinimapButton'
[string "@MissionReportButtonPlus/MissionReportButtonPlus.lua"]:272: in function <.../MissionReportButtonPlus/MissionReportButtonPlus.lua:103>

Locals:
self = MissionReportButtonPlusEventListenerFrame {
}
isCalledByUser = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
_log = <table> {
 USER = -10
 type = <table> {
 }
 INFO = 20
 DEBUG = 10
 NOTSET = 0
 level = -10
 DEVMODE = false
}
ns = <table> {
 dbg_logger = <table> {
 }
 AddonTitleShort = "MRBP"
 ExpansionInfo = <table> {
 }
 SLASH_CMD_ARGLIST = <table> {
 }
 isDebugActive = false
 settings = <table> {
 }
 L = <table> {
 }
 PlayerInfo = <table> {
 }
 AddonColor = <table> {
 }
 utilities = <table> {
 }
 utils = <table> {
 }
 HintIconCellProvider = <table> {
 }
 AddonTitleSeparator = ":"
 TextureCellProvider = <table> {
 }
 defaultSettings = <table> {
 }
 AddonTitle = "Mission Report Button Plus"
 data = <table> {
 }
 LandingPageInfo = <table> {
 }
}
L = <table> {
 CFG_DDMENU_NAMING_TEXT = "Prefer Expansion Names"
 CFG_ADDONINFOS_AUTHOR = "Author"
 showMawThreats = "Covenant Assaults"
 CFG_DDMENU_ENTRYTOOLTIP_GARRISON_INVASION_ALERT_TOOLTIP = "Shows an alert when an invasion in your Garrison is active."
 showLegionAssaultsInfo = "Legion Assault"
 CFG_DDMENU_ENTRYTOOLTIP_LABEL = "Details Tooltip"
 CFG_DDMENU_ENTRYTOOLTIP_MISSION_INFO_TOOLTIP = "Displays a brief summary of your currently active missions you started at the mission table."
 CFG_MAJOR_FACTION_SEPARATE_TOOLTIP_TEXT = "Use Separate Tooltip"
 CFG_DDMENU_NAMING_TOOLTIP = "The dropdown menu items are by default the names of each expansion.|n|nIf disabled, the name of each mission report will be displayed instead."
 ENTRYTOOLTIP_TIMEWALKING_VENDOR_LABEL = "Timewalking Vendor"
 ENTRYTOOLTIP_WORLD_MAP_EVENTS_LABEL = "World Map Events"
 CFG_DDMENU_ENTRYTOOLTIP_MAW_THREATS_TOOLTIP = "Displays a brief summary on the Covenant Assaults in The Maw."
 CFG_DDMENU_ENTRYTOOLTIP_SHOW_TOOLTIP = "On mouse-over each menu item details about the corresponding expansion are shown in a tooltip.|n|nIf disabled, this tooltip will not appear."
 applyInvasionColors = "Apply Invasion Colors"
 CFG_APPEARANCE_ANCHOR_DISTANCE_TOOLTIP = "Set the spacing between the menu frame and the minimap button."
 CFG_DDMENU_ENTRYTOOLTIP_FACTION_COLORS_TOOLTIP = "Displays the faction names in their respective colors."
 showGrandHuntsInfo = "Grand Hunts"
 CFG_DDMENU_STYLESELECTION_LABEL = "Menu Style"
 CFG_DDMENU_ENTRYTOOLTIP_DRAGON_GLYPHS_TOOLTIP = "Shows the progress of your Dragon Glyphs collection of each zone."
 CFG_DDMENU_STYLESELECTION_VALUE1_TEXT = "Tooltip Style"
 CFG_DDMENU_ENTRYTOOLTIP_BFA_BOUNTIES_TOOLTIP = "Lists the currently active Emissary Quests available on Zandalar and Kul Tiras in the tooltip."
 showCovenantBounties = "Callings"
 applyBfAFactionColors = "Apply Faction Colors"
 ENTRYTOOLTIP_LEGION_APPLY_INVASION_COLORS_LABEL = "Apply Invasion Colors"
 CFG_DDMENU_ENTRYTOOLTIP_EVENT_POI_ISKAARA_FEAST = "the Community Feast of the Iskaara Tuskarr"
 TOC_FILE_NOTES = "Adds a right-click menu to the mission reports button on the minimap|nwith access to reports from current and previous expansions."
 showBfAFactionAssaultsInfo = "Faction Assaults"
 CFG_DDMENU_ENTRYTOOLTIP_EVENT_POI_TIME_RIFTS = "the Time Rifts in Thaldraszus"
 CFG_DDMENU_ENTRYSELECTION_TEXT_D = "%d |4menu item:menu items; selected"
 showNzothThreats = "N'Zoth Assaults"
 CFG_DDMENU_ENTRYTOOLTIP_EVENT_POI_HIDE_EVENT_DESCRIPTIONS = "Hides additional event description texts when enabled."
 CFG_DDMENU_ENTRYTOOLTIP_EVENT_POI_SUPERBLOOM = "the Superbloom in the Emerald Dream"
 CFG_DDMENU_ENTRYTOOLTIP_EVENT_POI_DREAMSURGE = "the Dreamsurge on the Dragon Isles"
 CFG_APPEARANCE_DIMENSIONS_LABEL = "Dimensions"
 CFG_APPEARANCE_ANCHOR_POINT_MENU_TOOLTIP = "Set the menu frame's anchor point."
 CFG_APPEARANCE_ANCHOR_LABEL = "Anchor Point"
 CFG_DDMENU_SORTORDER_TOOLTIP = "The dropdown menu items are sorted by expansion release date; eg. the current expansion comes first, the one before that next, etc.|n|nIf enabled, the sorting order will be reversed."
 CFG_APPEARANCE_DIMENSIONS_FRAME_WIDTH_TOOLTIP = "Set the minimum width for the menu frame."
 autoHideCompletedDragonGlyphZon

**Comment by erglo** [comment]
Hi, thank you for reporting this!
I did quite some updating in the last days but couldn't finish everything prior to the today's release of WoW `11.0.2`. 
Since I don't have currently any errors, I might have fixed yours as well. If not, please keep me posted!

**Comment by nancikennedy** [comment]
This fixed the problem!

**Comment by erglo** [comment]
I'm glad to hear that! Thank your for the update!
