### ISSUE TITLE
Broken again with TWW 11.0.2

### ISSUE THREAD

**Issue by Flanell88** [erglo/wow-mission-report-button-plus#26]
Really sad to say, but its not working again with the latest 11.0.2 patch :(. Blizzard really hates Addon creators and users ...

**Comment by erglo** [comment]
Fixed. Blizzard removed a lot of deprecated code. I think many Addons broke today. I usually address this changes with each release, but I overlooked one. - Enjoy!

PS. Thanks again for reporting this, btw.
