### ISSUE TITLE
Odd behavior after latest update/hotfixes

### ISSUE THREAD

**Issue by AutolycusWolf** [erglo/wow-mission-report-button-plus#29]
Blizzard broke things up yet again with their latest series of updates/hotfixes. You can't see the Dragonflight button or window and it shows Shadowlands covenant no matter your choice. I'm also keep getting the following errors: 

Error No 1
3x .../Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua:663: Setting variable 'showAddonNameInTooltip' was previously registered.
[string "=[C]"]: in function `error'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:663: in function `RegisterSetting'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsInbound.lua"]:198: in function <...lizzard_Settings_Shared/Blizzard_SettingsInbound.lua:155>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsInbound.lua"]:98: in function <...lizzard_Settings_Shared/Blizzard_SettingsInbound.lua:97>
[string "=(tail call)"]: ?
[string "@MissionReportButtonPlus/MissionReportButtonPlus_Options.lua"]:244: in function <...ReportButtonPlus/MissionReportButtonPlus_Options.lua:238>
[string "@MissionReportButtonPlus/MissionReportButtonPlus_Options.lua"]:391: in function <...ReportButtonPlus/MissionReportButtonPlus_Options.lua:378>
[string "@MissionReportButtonPlus/MissionReportButtonPlus_Options.lua"]:418: in function <...ReportButtonPlus/MissionReportButtonPlus_Options.lua:414>
[string "@MissionReportButtonPlus/MissionReportButtonPlus_Options.lua"]:1084: in function `MRBP_Settings_Register'
[string "@MissionReportButtonPlus/MissionReportButtonPlus.lua"]:334: in function `OnLoad'
[string "@MissionReportButtonPlus/MissionReportButtonPlus.lua"]:114: in function <.../MissionReportButtonPlus/MissionReportButtonPlus.lua:107>

Locals:
(*temporary) = "Setting variable 'showAddonNameInTooltip' was previously registered."
 
Error No 2
3x ...ddOns/Blizzard_Settings_Shared/Blizzard_Settings.lua:347: attempt to call method 'GetVariableType' (a nil value)
[string "@Blizzard_Settings_Shared/Blizzard_Settings.lua"]:347: in function `CreateCheckboxInitializer'
[string "@Blizzard_Settings_Shared/Blizzard_Settings.lua"]:371: in function <...ddOns/Blizzard_Settings_Shared/Blizzard_Settings.lua:370>
[string "=(tail call)"]: ?
[string "@MissionReportButtonPlus/MissionReportButtonPlus_Options.lua"]:393: in function <...ReportButtonPlus/MissionReportButtonPlus_Options.lua:378>
[string "@MissionReportButtonPlus/MissionReportButtonPlus_Options.lua"]:418: in function <...ReportButtonPlus/MissionReportButtonPlus_Options.lua:414>
[string "@MissionReportButtonPlus/MissionReportButtonPlus_Options.lua"]:1084: in function `MRBP_Settings_Register'
[string "@MissionReportButtonPlus/MissionReportButtonPlus.lua"]:334: in function `OnLoad'
[string "@MissionReportButtonPlus/MissionReportButtonPlus.lua"]:114: in function <.../MissionReportButtonPlus/MissionReportButtonPlus.lua:107>

Locals:
setting = <table> {
 searchTags = <table> {
 }
 data = <table> {
 }
 modifyPredicates = <table> {
 }
 frameTemplate = "SettingsCheckboxControlTemplate"
}
options = nil
tooltip = "If enabled, the add-on name abbreviation will be displayed in the minimap button's tooltip."
(*temporary) = nil
(*temporary) = <table> {
 searchTags = <table> {
 }
 data = <table> {
 }
 modifyPredicates = <table> {
 }
 frameTemplate = "SettingsCheckboxControlTemplate"
}
(*temporary) = "attempt to call method 'GetVariableType' (a nil value)"

**Comment by erglo** [comment]
Hi, thank you for reporting this!
I will look into it. I didn't have the time to adjust my addon to the new expansion, yet. There are a lot of changes to be made, but I'm on it.

**Comment by erglo** [comment]
Hi, I just released a new version. The addon should work now.
In case the War Within expansion isn't shown in the minimap button's menu, try going to settings and de-/activate it manually.
- Enjoy!
